namespace castledice_game_server.GameController.GameInitialization.GameCreation.GameCreationProviders.BoardConfigProviders.ContentSpawnersProviders.TreesSpawning;

public interface ITreesGenerationConfigProvider
{
    TreesGenerationConfig GetTreesGenerationConfig();
}