namespace castledice_game_server.GameController.GameInitialization.GameCreation.GameCreationProviders.BoardConfigProviders.CellsGeneratorsProviders;

public interface IRectGenerationConfigProvider
{
    RectGenerationConfig GetRectGenerationConfig();
}